---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-firefly
  labels:
    app: firefly-iii
spec:
  selector:
    app: firefly-iii
    tier: phpmyadmin
  type: NodePort
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-firefly
  labels:
    app: firefly-iii
spec:
  selector:
    matchLabels:
      app: firefly-iii
      tier: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly-iii
        tier: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: firefly-iii-mysql
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-iii-secrets
                  key: db_password